### PR TITLE
Update climate.py

### PR DESCRIPTION
**Pull request by idisis**
Add missing properties so that Google Assistant can control A/C temperature.

### CODE REVIEW

**Comment by idisis** [comment]
The change has been tested and works properly.
Google assistant was able to control the A/C temperature after this change.

**Comment by yonatanp** [comment]
@idisis , are you sure this change works? It looks as if you're calling() the `target_temperature` property as if it was a method. Am I missing something?

**Comment by idisis** [comment]
Hi,
Sorry about that.
I fixed it locally on my end and then re-typed it straight on github,
instead of cloning the repo.
Nice catch though :)

But I found that the fix needs some more work.
Originally, the assistant could increase/decrease the temperature (Hi
Google, warm up/cool down ...).
This fix allows you to specify the desired temperature (Hi Google, set ...
temperature to 25 degrees).
But it also implicitly changes the A/C mode to auto (heat/cool).
It makes sense, as in HA the temperature range is a feature of the auto
mode...

I'll make another PR with a more complete solution.

**Comment by yonatanp** [comment]
Sounds good. I’m closing this PR for now.

**Pull request closed without merging**
