### PR TITLE
Have Multiple ACs under a single setting + Async Initialization

### LINKED ISSUE #1: Idea: Have multiple ACs per configuraion
I have 4 ACs at home,
Using the same imei and token.
but multiple ACs

```
climate:
  - platform: electrasmart
    imei: "2b9500000..."
    token: "1fd4a2e86..."
    acs: 
        - ac_id: 12345
           name: MyLivingRoomAC
        - 23456
           name: BedroomAC
```

### PR DESCRIPTION
**Pull request by GuyKh**
Fixes #1 and #2

### CODE REVIEW

**Comment by yonatanp** [comment]
Looks good! Were you able to verify it on a multi-AC setup?

**Comment by GuyKh** [comment]
@yonatanp yeah - got it up and running for multiple ACs
The only part that the configuration is not backward compatible...

**Comment by yonatanp** [comment]
Yes, that's the only thing that troubles me. Not like there's a lot of users, but still, do you know maybe how to optionally detect that old config is being used and load from it? We can keep the README on new alone and get rid of back-compat after a while.

**Comment by yonatanp** [comment]
Let's not block the PR for this. You're welcome to push a back-compat fix if/when you feel like it.

**Pull request merged**
